### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by hitstergtd** [CoolerVoid/cooler_sse42_strcmp#1]
@CoolerVoid,

Thanks for the brilliant code and the accompanying article on your blog. I was wondering if it is possible that you might consider changing the license of your code to MIT / 2-clause BSD?

It would be really appreciated and make it easier to adopt your work into other projects, especially other open source libraries, etc.

Thanks again!

**Comment by hitstergtd** [comment]
@CoolerVoid Any thoughts?

**Comment by CoolerVoid** [comment]
Ok thanks... you can use it... 
I change to BSD... https://github.com/CoolerVoid/cooler_sse42_strcmp/blob/master/LICENSE.txt

its Ok ?

**Comment by hitstergtd** [comment]
@CoolerVoid,
Thanks a lot! It is appreciated. 👍
