### ISSUE TITLE
Tiny improvement on strcmp_sse42_64.s

### ISSUE THREAD

**Issue by fredericopissarra** [CoolerVoid/cooler_sse42_strcmp#2]
Just get rid of unecessary prologue and epilogue... :)
And xor rax,rax can be changed to xor eax,eax...

https://ghostbin.com/paste/rsp32

[[]]s
Fred

**Comment by CoolerVoid** [comment]
OK master,  thank you
on the weekend i fix it...

One doubt, in point of xor eax...  i guess that NASM can say warning because EAX is not 64 register... i gonna test it...

**Comment by fredericopissarra** [comment]
On x86_64 if you assign any value to a 32 bit register, the upper 32 
bits are zeroed... So,

XOR EAX,EAX will create a 2 byte instruction, but will zero all RAX 
register.
XOR RAX,RAX is the sabe instruction with 0x48 prefix.

PS: MOV EAX,0 will set the entire RAX to 0 as well... But MOV RAX,0 will 
be optimized by NASM to MOV EAX,0. BTW, ANY positive value smaller then 
0xffffffff will be optimzed... try MOV RAX,-1 and MOV EAX,-1 to see the 
difference...

1                                  bits 64
   2
   3 00000000 B800000000              mov eax,0
   4 00000005 B800000000              mov rax,0
   5 0000000A 31C0                    xor eax,eax
   6 0000000C 4831C0                  xor rax,rax


[]s

**Comment by CoolerVoid** [comment]
Very good
Thank you
