### ISSUE TITLE
Possible bug...

### ISSUE THREAD

**Issue by fredericopissarra** [CoolerVoid/cooler_sse42_strcmp#3]
Are you sure you can use 32 bytes as displacement when loading xmm0 in strcmp_sse42_64() code? XMM registers are 16 bytes long!

**Comment by CoolerVoid** [comment]
I know this fact... At logic, 32 is YMM 256bit... but... 
First at 64 version i using 16 like 32bit version, but i try put 32 in 64bit version and i make benchmark runs faster than 16... is very curious! i am using i5 haswell..
https://github.com/CoolerVoid/cooler_sse42_strcmp/blob/master/strcmp_sse42_32.s#L19

**Comment by fredericopissarra** [comment]
Well... did you tried to compare strings like:

"0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF" and
"0123456789ABCDEFFEDCBA98765432100123456789ABCDEFFEDCBA9876543210"?

The first 16 bytes portion of the 32 bytes chunck are equal and, If 
strcmp_sse42_64() says they are "equal" there is the answer to why is 
that fast! ;)

**Comment by CoolerVoid** [comment]
Its OK
i change again to 16...

cheers
